### ISSUE TITLE
import styles?

### ISSUE THREAD

**Issue by darewreck54** [jaysoo/todomvc-redux-react-typescript#19]
I'm not sure if this is an issue, or just my inexperience with webpack and how it's configured for project.

How do you import a css into the project.  There is normally two ways:
1) Using import styles from <css file location>
2) Using require (<css file>)

However, in both cases it doesn't work.  In the webpack it seems that it does add the styles!css loader.

Any advice appreciated,
Thanks,
Derek

**Comment by jaysoo** [comment]
@darewreck54 Hey, the webpack config was missing an entry to handle CSS since it is out of scope in this project. However, I have just added it with the latest webpack2 upgrade.

You should be able to import CSS files the same way as JS/TS/TSX files now. (e.g. import './test.css';)
