### ISSUE TITLE
Possible see the uncompiled tsx files in chrome dev tools? 

### ISSUE THREAD

**Issue by lukephills** [jaysoo/todomvc-redux-react-typescript#3]
Thanks for the tutorial and example. 

I was wondering if you new how to see the uncompiled tsx files in chrome dev tools? 

For instance, i put a console log in Header.tsx. The console will log something out, I click "Header.tsx" on the right and it'll open up Header.tsx in the sources tab. It's been compiled to javascript when it would be nicer to view the tsx unchanged.

Is there any way to change the sourcemaps so this can work?

**Comment by jaysoo** [comment]
Hi @lukephills, I just pushed a coupe of changes to `master` to enable sourcemaps. You basically need to enable sourcemaps for typescript compiler, and also for webpack.

See https://github.com/jaysoo/todomvc-redux-react-typescript/commit/9e5e88b177b6ddc477b413efbb96b76a193a7d45

**Comment by lukephills** [comment]
Amazing! That works, thanks for your help!
