### ISSUE TITLE
PR for typings, and Redux TS definition file

### ISSUE THREAD

**Issue by mikekidder** [jaysoo/todomvc-redux-react-typescript#5]
Was wondering if you would interested in a PR to migrate to typings, since tsd is deprecated?

Also, looks like that Redux with reactjs/redux#1413 is getting an official Typescript definition file. Interested to giving some input?

**Comment by jaysoo** [comment]
@mikekidder That sounds like a great idea. If you have a PR ready I'll definitely give it a look! :)

Otherwise it might take me another few days to change over due to other commitments.

**Comment by jaysoo** [comment]
@mikekidder Updated project to use typings instead of tsd.
