### ISSUE TITLE
bindActionCreators is discouraged to use in Redux docs

### ISSUE THREAD

**Issue by Ciantic** [jaysoo/todomvc-redux-react-typescript#7]
I'm trying to figure out Redux and what are best practices using it. From it's documentation one gets an impression bindActionCreators is not a good practice:

> **Normally you should just call dispatch directly on your Store instance.** If you use Redux with React, react-redux will provide you with the dispatch function so you can call it directly, too.
> 
> The only use case for bindActionCreators is when you want to pass some action creators down to a component that isn’t aware of Redux, and you don’t want to pass dispatch or the Redux store to it.

Emphasis mine, [see documentation for more information](http://redux.js.org/docs/api/bindActionCreators.html).

However, at the moment I don't know what is the preferred alternative to bindActionCreators.

**Comment by Ciantic** [comment]
The Redux examples are conflicting, their [real-world example](https://github.com/reactjs/redux/tree/master/examples/real-world) doesn't use bindActionCreators but their [todomvc example](https://github.com/reactjs/redux/tree/master/examples/todomvc) does use it.

I think the question for now is, which one is more type-safe approach.

**Comment by Ciantic** [comment]
I will close this, not an issue in this repo since this just reimplements same todomvc as in Redux examples, which also use bindActionCreators.

**Comment by jaysoo** [comment]
@Ciantic Hey, noticed you close the issue but I want to give a reply anyway. I think it probably makes more sense to call action creators directly inside the component, and pass the result to `dispatch`. This means you can get all of the type safety of your own action creators (because `bindActionCreators` is unsafe).

I will update the example to reflect this change.

**Comment by Ciantic** [comment]
Cool, thanks. I'm still learning redux and sametime trying to figure out what is the most type-safe way to do redux, since it's not built type-safety in mind it's hard to find material for it.

**Comment by jaysoo** [comment]
@Ciantic I pushed the changes to master.

See: https://github.com/jaysoo/todomvc-redux-react-typescript/blob/master/client/containers/App.tsx#L24-L28

Basically, now that I am calling my own action creators directly, I can guarantee type safety of the parameters. When calling methods on result of `bindActionCreators` you lose all safety.

:)

**Comment by Ciantic** [comment]
FYI, if you are interested on more about TypeScript way of doing Redux. I just found out these: https://github.com/alm-tools/alm/blob/master/docs/contributing/REDUX.md  and  https://github.com/alm-tools/alm/blob/master/src/app/state/simpleRedux.ts by @basarat who seems to pull impossible hours working on TypeScript related projects.

**Comment by basarat** [comment]
🌹 Thanks!

**Comment by eapyl** [comment]
Hi, why master/client/main.tsx contains bindActionCreators ? is it needed ? thanks

**Comment by jaysoo** [comment]
@Udgin Nope, just updated. :)
