### ISSUE TITLE
Latest typings has changed, breaks the repo

### ISSUE THREAD

**Issue by mikecann** [jaysoo/todomvc-redux-react-typescript#9]
Latest typings uses the term "global" instead of "ambient".

Simply changing typings.json from ambient to global doesnt seem to fix it tho.

**Comment by mikecann** [comment]
Fixed and submitted a PR: https://github.com/jaysoo/todomvc-redux-react-typescript/pull/10

**Comment by jaysoo** [comment]
@mikecann Thanks, appreciate it! 💯
